# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Project 4 - Simple Stopwatch' do
pod 'Font-Awesome-Swift', '~> 1.4.5'
end

